D8CORE-2102: add check to see if the path is part of the url
SU-SWS/stanford_basic pull request #190
Opened 2020-10-09 18:04 UTC by imonroe

# READY FOR REVIEW

# Summary
- In the menu, the active item is set by checking if the URL is identical to the path of the menu item. Here, we add a check to see if the menu item path is part of the URL.

# Review By (Date)
- next week.

# Urgency
- 1 out of 10

# Steps to Test

1. Check out this branch
2. `drush cr`.
3. Create a news story
4. Visit `/news`.  Notice the "News" item in the main menu is active.
5. Click through to the news story you created.  Notice that the "News" in the main menu is still active.

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2020-10-13 20:22 UTC, sherakama submitted a review, later dismissed
OK by me.

2020-10-16 00:57 UTC, jenbreese requested changes
Hi @imonroe, I noticed it isn't working on the mobile view. Thanks! Jen

2020-10-16 15:10 UTC, jenbreese commented
I did more testing. The news/article example works. On desktop view the Home link, the indicator works. On the mobile/responsive menu, the indicator is not there. 
<img width="760" alt="Screen Shot 2020-10-16 at 8 10 15 AM" src="https://user-images.githubusercontent.com/1187335/96275810-0becc500-0f87-11eb-8d49-3fb78e9e1e52.png">
<img width="1231" alt="Screen Shot 2020-10-16 at 8 09 53 AM" src="https://user-images.githubusercontent.com/1187335/96275816-0ee7b580-0f87-11eb-832d-82413960d968.png">
<img width="860" alt="Screen Shot 2020-10-16 at 8 09 43 AM" src="https://user-images.githubusercontent.com/1187335/96275821-1018e280-0f87-11eb-80e4-35ccedf7fffb.png">

2020-10-16 16:17 UTC, imonroe commented
Ok, I fixed the issue with the Home link on mobile.  However, it's easy to see how this can lead to infinite regress if we're not careful with how we apply the `is_active` flag. E.g., the `People` menu item correctly is set to active when you're on the `/people` page, however, if you drill down to an individual, you'll find the menu path is `/person/john-doe` or whatever, and the path matching breaks.  We could build a lookup array with the basic menu items, but that's going to break as soon as folks start manipulating the contents of the menu on their individual sites.

2020-10-16 16:20 UTC, sherakama commented on stanford_basic.theme
> +        ($item_path == '/home' && $current_path == '/')) {
I don't think we can assume home here. I've seen other paths used as well. You likely will have to get the alias from the site settings instead of assuming `/home`

2020-10-16 16:29 UTC, imonroe commented on stanford_basic.theme
> +        ($item_path == '/home' && $current_path == '/')) {
@sherakama what about something like `\Drupal::service('path.matcher')->isFrontPage()`?

2020-10-16 16:31 UTC, sherakama commented on stanford_basic.theme
> +        ($item_path == '/home' && $current_path == '/')) {
That might do it.

2020-10-16 16:48 UTC, imonroe commented on stanford_basic.theme
> +        ($item_path == '/home' && $current_path == '/')) {
Adjusted to allow for alternate front pages.

2020-10-19 15:56 UTC, jenbreese commented
@imonroe That fixed the highlight for "Home" on my dev for mobile. It is still working as expected for the desktop size.

2020-10-19 16:54 UTC, sherakama commented on stanford_basic.theme
> +        ($item['title'] == 'Home' && \Drupal::service('path.matcher')->isFrontPage())) {
Do we need to check the title as well?

2020-10-19 17:21 UTC, imonroe commented on stanford_basic.theme
> +        ($item['title'] == 'Home' && \Drupal::service('path.matcher')->isFrontPage())) {
@sherakama I'm not sure I understand exactly what you mean.  What we're checking here is that the title of the menu item is "Home", and the page we are actually on is set as the current front page.  We can check the title of the current front page to make sure it is what we expect, but that seems redundant, yeah?  The title of the current front page is somewhat arbitrary, since the site owner can set it to any page they like...

2020-10-19 22:11 UTC, sherakama commented on stanford_basic.theme
> +        ($item['title'] == 'Home' && \Drupal::service('path.matcher')->isFrontPage())) {
As the title for the link can be arbitrary, I was wondering if we want to check it at all? Shouldn't this function just try to match the URL, in whatever form it is in, to the current page/URL? It does appear the home page needs special handling as it could be `/home` `/` or perhaps even `<front>`

eg:
```
if (...->isFrontPage()) {
  $ops = ['/', '/home-page-alias', '/node/12345', '<front>'];
  if (in_array($item_path, $ops)) {
    $item['is_active'] = TRUE;
  }
}
```

2020-10-20 15:24 UTC, imonroe commented on stanford_basic.theme
> +        ($item['title'] == 'Home' && \Drupal::service('path.matcher')->isFrontPage())) {
I believe that the result of that code will be that if you are on the front page of the site, every link in the navigation menu will be marked as active.  

So, we're looking at `$item['title']` to know if we are manipulating the "Home" link in the menu.  The `$item_path` variable will be `/` for that, which we could target as well I suppose, which would allow the user to change the name of the "Home" link in the menu.  

To put it another way, if you are on the homepage of the site, regardless of what page that is, and you haven't changed anything in the menu, then: 
`$item['title']` == 'Home'` OR `$item_path == '/'` will both target the same button in the navigation menu, and `...->isFrontPage()` will return TRUE.

However, if the site owner has changed the link title in the menu, or has changed the link path in the menu, then one or both of those targets will no longer be useable.  

My thinking was that by targeting the button based on `$item['title']` == 'Home'` was slightly more robust, since a site owner who has changed their front page may have changed the link (the `$item_path`) to the page they want as the homepage, while leaving the text of the link (`Home`) alone.

2020-10-27 05:39 UTC, sherakama commented on stanford_basic.theme
> +        ($item['title'] == 'Home' && \Drupal::service('path.matcher')->isFrontPage())) {
I think we can ignore the text of the link for this check altogether. It is likely to be 'home' but not necessarily the case as you outlined above. From what I know, the home page could be a number of valid URLs and we will need to check for each type. Off the top of my head a few options are:

- `/` Root of the domain
- `/[base_path]` Where this site is configured to sit under a path under a TLD. eg: https://example.com/mysite/
- `/[alias]` Where alias is the node path alias
- `/node/[nid]` Path to the direct node
- `<front>` Special keyword
- `https://[vanity]'.stanford.edu` if the user does this they don't deserve highlighting.

I would rather see a check for those combinations of URLs instead of checking for a text label.

2020-11-02 18:21 UTC, imonroe commented on stanford_basic.theme
> +      $normal_path == '<front>') {
`base_path()` accounts for `/` or `/base/path/`
`$front_uri` accounts for `node/10`, etc.
`$alias` accounts for `/home`, etc.
`<front>` accounts for front, obvs.

2020-11-02 18:30 UTC, imonroe commented on stanford_basic.theme
> +        ($item['title'] == 'Home' && \Drupal::service('path.matcher')->isFrontPage())) {
@sherakama see notes on the update below.

2020-11-03 17:45 UTC, sherakama commented on stanford_basic.theme
> +      $normal_path == '<front>') {
This was a pain but thank you for doing it. This is much more robust.

2020-11-03 17:45 UTC, sherakama approved these changes
GTG

2020-11-03 17:46 UTC, merged