D8CORE-4037: fixed word wrapping with very long menu items
SU-SWS/stanford_basic pull request #226
Opened 2021-04-29 21:37 UTC by imonroe

# READY FOR REVIEW

# Summary
- In some, but not all, cases, long menu items weren't wrapping correctly when there was a submenu for the item.  This corrects that problem by adjusting the max-width for items that have a submenu below them, and removes the unnecessary width restriction when there is no submenu.

# Review By (Date)
- end of sprint
- 
# Urgency
- low 

# Steps to Test

1. check out branch, clear caches.
2. create some pages that have long titles, and set them up as drop down menus.
3. make several levels if you can.
4. verify that the long menu items wrap correctly both with submenus and without.

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2021-04-29 21:44 UTC, pookmish requested changes
The approach looks fine. but theres a couple issues if we can fix them:
The word is really close to the right edge.
![image](https://user-images.githubusercontent.com/7185045/116622236-3980d680-a8f9-11eb-90bc-aaa23deaf6fa.png)

Also if a page is unpublished, the indicator is mostly behind the menu item above it. probably just needs a higher z-index.

2021-04-29 22:05 UTC, imonroe commented
Looks like the z-index thing is an existing bug.  just setting the z-index doesn't fix it, because it's got CSS animation on it, and that re-sets the z-index to 0 when it redraws.  I'm trying to see if I can find a fix, but it's trickier than it seemed.

2021-04-29 22:34 UTC, imonroe commented
I fixed the margin for items that have no sub menu, but I'm lost on the stacking thing.  Because the opacity is adjusted as part of the css animation, it always resets the z-index to `auto`, and I don't know how to make it not do that, since it's in the css specs.  @jenbreese do you have an idea?  example:

![image](https://user-images.githubusercontent.com/1263892/116626595-c1221180-a908-11eb-9971-d73908196f0c.png)

2021-05-03 22:10 UTC, jenbreese commented
@imonroe  Try adding this on _menu.scss at link line
`.su-multi-menu__item--expanded {
  .unpublished-indicator {
    top: 0;
  }
}`

2021-05-03 23:13 UTC, imonroe commented
That did the trick!  Thanks very much Jen!

2021-05-05 23:47 UTC, pookmish requested changes

2021-05-05 23:47 UTC, pookmish commented on src/scss/admin/_menu.scss
> +.su-multi-menu__item--expanded { .unpublished-indicator { top: 0; } }
a couple things here
1. move this to the [admin scss](https://github.com/SU-SWS/stanford_basic/blob/8.x-5.x/src/scss/admin/_menu.scss#L19)
2. this doesn't look good as it overlays on top of the link text. This can easily be fixed by removing the [`overflow: hidden](https://github.com/SU-SWS/stanford_basic/blob/8.x-5.x/src/scss/components/multi-menu/_multi-menu.scss#L277) and positions the indicator in the normal position

2021-05-05 23:49 UTC, pookmish commented
Still an issue with the spacing 
![image](https://user-images.githubusercontent.com/7185045/117223105-d3e18e00-adc1-11eb-8364-5923802136b6.png)

2021-05-06 15:10 UTC, jenbreese commented on src/scss/admin/_menu.scss
> +.su-multi-menu__item--expanded { .unpublished-indicator { top: 0; } }
I'm curious, do you mean the 'overflow: hidden' on the parent 'li'? In my test, when I remove that it changes the width of the indictor. I don't know if it was intentional to narrow that indicator?

2021-05-06 16:06 UTC, imonroe commented
> Still an issue with the spacing
> ![image](https://user-images.githubusercontent.com/7185045/117223105-d3e18e00-adc1-11eb-8364-5923802136b6.png)

Again, I think you may not have the newest version of the CSS pulled in, or maybe something is cached.  I can't reproduce with that same title: 

![image](https://user-images.githubusercontent.com/1263892/117330193-aabd0e00-ae52-11eb-9068-32b7055f9667.png)

2021-05-06 16:08 UTC, imonroe commented
I can pull that max-width in a few more pixels; it might be differences in the way your linux browser is drawing the fonts, etc, because I cut that edge off as close as I could to the drop-down toggle to make it as wide as possible.

2021-05-06 16:30 UTC, imonroe commented on src/scss/admin/_menu.scss
> +.su-multi-menu__item--expanded { .unpublished-indicator { top: 0; } }
Actually, removing overflow:hidden there obviates the need for the additional `top: 0;` all together.  I see what Jen means about the active indicator getting a pixel or two wider, but I think it actually looks a little better that way.  It makes it the same width as the active trail indicator.  I've made the change.

2021-05-06 16:35 UTC, imonroe commented
I reduced the width of the text-wrapper and I removed `overflow:hidden` from the `li` element.  Should be good now.

2021-05-06 16:46 UTC, pookmish approved these changes
Ok this looks good to me now :+1:

2021-05-06 16:46 UTC, merged