D8CORE-3502 - a11y fixes for nav menu
SU-SWS/stanford_basic pull request #227
Opened 2021-05-04 17:28 UTC by imonroe

# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2021-05-04 19:32 UTC, jenbreese commented
@imonroe Does this PR have the long title fix in it?

2021-05-04 19:48 UTC, jenbreese commented
@imonroe here you said `the aria-label on the drop down toggles no longer says "expand menu", but rather mentions the name of the menu the toggle opens.`. On my local, it still says "expand menu"

2021-05-04 20:28 UTC, imonroe commented
> @imonroe here you said `the aria-label on the drop down toggles no longer says "expand menu", but rather mentions the name of the menu the toggle opens.`. On my local, it still says "expand menu"

Make sure you clear your browser cache.  In Chrome, open the dev tools, and then right click the "reload" button in the address bar.  that'll bring up an option to clear caches and hard reload.

2021-05-04 20:29 UTC, imonroe commented
> @imonroe Does this PR have the long title fix in it?

That one is in the other PR. https://github.com/SU-SWS/stanford_basic/pull/226

2021-05-04 20:49 UTC, jenbreese commented
Hi @imonroe I tried a couple times clearing the caches and reloading and clearing the browser cache. I still am getting `expand menu`.
<img width="481" alt="Screen Shot 2021-05-04 at 1 48 40 PM" src="https://user-images.githubusercontent.com/1187335/117068010-94427580-acdf-11eb-9539-791e4a5a5e50.png">

2021-05-04 23:27 UTC, imonroe commented on src/js/components/secondary-nav/buttons/SubNavToggle.js
> +    // Label the toggle to indicate what menu it opens
@jenbreese This was the part that was missing.  It was still in my undo buffer, so a CTRL-Z or three got it back for me.

2021-05-05 04:44 UTC, jenbreese commented on src/js/components/secondary-nav/buttons/SubNavToggle.js
> +    // Label the toggle to indicate what menu it opens
@imonroe So I was testing tonight. The aria-label on the drop down toggle worked on Mac/Chrome. All the other aspects worked too.  For Firefox,  the aria-label does not work on Mac, or on Windows (browserstack). The escape key does work and the aria-expanded is on the right element.  I tried it on Edge and Windows (browserstack and everything worked.  Looks like FF is the problem for that label. :)

2021-05-05 23:21 UTC, imonroe commented on src/js/components/secondary-nav/buttons/SubNavToggle.js
> +    // Label the toggle to indicate what menu it opens
I found the bug and fixed it.  I've gotta remember to use FF only when writing JS; it's so picky.

2021-05-05 23:50 UTC, pookmish requested changes
This doesn't appear to work correctly. It concats  all the parent menu items togeather for child button aria labels 
![image](https://user-images.githubusercontent.com/7185045/117223196-fd9ab500-adc1-11eb-9afb-3fa6b7ad6b21.png)

2021-05-06 15:54 UTC, imonroe commented
> This doesn't appear to work correctly. It concats all the parent menu items togeather for child button aria labels
> ![image](https://user-images.githubusercontent.com/7185045/117223196-fd9ab500-adc1-11eb-9afb-3fa6b7ad6b21.png)

I believe you don't have the latest version, or you didn't clear your caches.  That was happening in an earlier version of the code, but I fixed it.

![image](https://user-images.githubusercontent.com/1263892/117328698-1bfbc180-ae51-11eb-8a20-715d1c5f9431.png)

2021-05-06 17:47 UTC, pookmish commented
It appears pulling the latest commits fixed some of it, but I don't believe there's a need to concat the parent menu item to the current one. "Open the [menu item] menu" not "Open the [parent item]+[menu item] menu" makes very long read out for the users when you get down to the 3rd and 4th levels.

2021-05-06 20:53 UTC, imonroe commented
@pookmish I found a simpler way of grabbing the link text from the link, and it fixed the problem with the concatenated menu names.  Should be g2g now.

2021-05-06 20:55 UTC, pookmish commented
@imonroe ok that does work better. but the "Open" word doesn't change when the menu is open vs closed. The language should change depending if the submenu is open or not.

2021-05-06 20:56 UTC, imonroe commented
> @imonroe ok that does work better. but the "Open" word doesn't change when the menu is open vs closed. The language should change depending if the submenu is open or not.

How about if we just change it to "toggle" instead?  covers both situations.

2021-05-06 20:58 UTC, pookmish commented
> How about if we just change it to "toggle" instead? covers both situations.

The language needs to change. A visually impaired user won't know if the sub menu is open or not based on "Toggle"

2021-05-06 22:56 UTC, imonroe commented
> > How about if we just change it to "toggle" instead? covers both situations.
> 
> The language needs to change. A visually impaired user won't know if the sub menu is open or not based on "Toggle"

Ok, I added an Observer to watch for changes in the aria-expanded, and if it finds one, it triggers a label change based on the current state.  Works pretty well for me.  Lemme know if that's sufficient, @pookmish .

2021-05-06 23:04 UTC, pookmish approved these changes
This looks good to me now. Thanks for working through those fixes :+1:

2021-05-06 23:05 UTC, merged

2021-05-06 23:05 UTC, imonroe commented on src/js/components/secondary-nav/buttons/SubNavToggle.js
> +    this.observer = new MutationObserver(function () {
it's vanilla JS, which is convenient.

2021-05-10 16:18 UTC, sherakama commented on src/js/components/secondary-nav/buttons/SubNavToggle.js
> +    this.observer = new MutationObserver(function () {
Cool: https://caniuse.com/mutationobserver